input-output-hk/js-cardano-wasm

- build
Current build script is not working for me. I'm getting the following error:
```bash
$ ./build 
./build: 4: ./build: pushd: not found
error: could not find `Cargo.toml` in `/home/Projects/iohk/icarus-poc/js-cardano-wasm` or any parent directory
./build: 6: ./build: popd: not found
```
It seems to be related to the [following issue](https://stackoverflow.com/questions/5193048/bin-sh-pushd-not-found). I fixed it changing the shell to bash.
> Fix build script

- js/Wallet.js
- wallet-wasm/src/lib.rs
now, instead of returning only the cbor encoded transaction and witnesses, it also returns the transaction and witnesses.
```
> JSON.stringify(result.tx.tx, null, 4);
"{
"inputs": [
{
"id": "1c7b178c1655628ca87c7da6a5d9d13c1e0a304094ac88770768d565e3d20e0b",
"index": 42
}
],
"outputs": [
{
"address": "DdzFFzCqrhtCUjHyzgvgigwA5soBgDxpc8WfnG1RGhrsRrWMV8uKdpgVfCXGgNuXhdN4qxPMvRUtbUnWhPzxSdxJrWzPqACZeh6scCH5",
"value": 666
},
{
"address": "DdzFFzCqrhtCUjHyzgvgigwA5soBgDxpc8WfnG1RGhrsRrWMV8uKdpgVfCXGgNuXhdN4qxPMvRUtbUnWhPzxSdxJrWzPqACZeh6scCH5",
"value": 166719
},
{
"address": "DdzFFzCqrhtCUjHyzgvgigwA5soBgDxpc8WfnG1RGhrsRrWMV8uKdpgVfCXGgNuXhdN4qxPMvRUtbUnWhPzxSdxJrWzPqACZeh6scCH5",
"value": 92669963
}
]
}"
```
> return the details of the transaction when creating a ready to send tx

- js-example/src/Components/Bindings/BIP39.js
- js/Wallet.js
- wallet-wasm/src/lib.rs
> No feeaddr in wallet spend's API

- js/tests/random-address-checker.js
- Removed sleep, Instead we are returning a promise in `before` hook
- Restructured the steps in order to avoid nested `describe`
> Remove sleep from tests

- build
This returns an error if `rustup` or `cargo` invocation fails
> Fail if toolchain is not installed

- wallet-wasm/src/lib.rs
this will save some space for larger cbor encoded txaux
> remove the JSON serialised TxAux from the spend output

- wallet-wasm/Cargo.toml
Added code size optimalization based on:
https://rustwasm.github.io/book/game-of-life/code-size.html
it should go from:
```
Asset     Size  Chunks                    Chunk Names
./dist/index.js  8.51 MB       0  [emitted]  [big]  index
./dist/index.js.map  8.63 MB       0  [emitted]         index
```
to:
```
Asset     Size  Chunks                    Chunk Names
./dist/index.js  2.38 MB       0  [emitted]  [big]  index
./dist/index.js.map   2.5 MB       0  [emitted]         index
```
> Add size optimalization

- wallet-wasm/Cargo.toml
In Emurgo we are working in libraries to implement the c-bindings for iOS and Android. Instead of copy-pasting the code from this repo, it would be awesome if we could reuse it by adding this repo as a `git submodule` :). This change allows the compilation to a rust lib.
> Allows compilation to Rust Lib

- wallet-wasm/Cargo.toml
There is a problem when adding lib because it disables lto for cdylib :( https://github.com/rust-lang/cargo/issues/2301
sorry about that 🙈
> Restore Cargo.toml to previous configuration

- js/Wallet.js
Account var is duplicating in object declaration like `{ account, account }`, it constantly gets highlighted in my IDE as error, and I always forget to propose a fix )
> Replaced erroneous comma with a colon 

- js/Redemption.js
- js/index.js
- js/tests/redemption.js
- package.json
- wallet-wasm/src/lib.rs
Added couple of functions to `wasm-wallet/lib.rs` implementing required functionality:
1. Converting private redemption key to redemption address
2. Producing a redemption transaction
> Redemption features to old API

- js/tests/redemption.js
- wallet-wasm/src/lib.rs
Replaced mock signature by actual witness creation (and updated rust dependency revision)
> Updating redemption stuff in old API to redemption witness in rust-cardano

- js/Redemption.js
- js/tests/redemption.js
- wallet-wasm/src/lib.rs
This feature is required to convert all avvm keys from the genesis block into transaction outputs.
1. Implemented `redemption_public_to_avvm_tx_out` in Rust
2. Implemented `redemptionPubKeyToAvvmTxOut` connector in JS
3. Implemented new test and fixed previous tests
For new test used actual publicly known IOHK redemption public key from the genesis and compared with the actual known address: `Ae2tdPwUPEZKQuZh2UndEoTKEakMYHGNjJVYmNZgJk2qqgHouxDsA5oT83n `.
Also fixed line in Rust where `Coin` were dereferences, since latest `rust-cardano` doesn't do it anymore.
> Generate input-tx and address by redemption public key

- cardano-wallet/Cargo.toml
this version is now bundled to npmjs.com registry as a nodejs package.
> publish nodejs compiled package

- js/Wallet.js
- wallet-wasm/src/lib.rs
We had the two following existing functions:
1) Restoring V1 wallet from mnemonic
1) Restoring V2 wallet from master key
I joined the two together to make a new function "restoring V1 wallet from master key"
This is useful because it allows Daedalus users who forgot their mnemonic but remember their password to recover their wallet
> add restore from daedalus master key

- cardano-wallet/package.json
- cardano-wallet/tests/index.js
- cardano-wallet/webpack.config.js
Without this change, running `npm run webpack-dev-serve` will result in the following two errors:
```
TypeError: TextEncoder is not a constructor
TypeError: TextDecoder is not a constructor
```
This will not help you if you get the error `__webpack_require__(...).readFileSync is not a function`. For that one you need to build the wasm bindings in browser mode.
> Fix TextEncoder/TextDecoder issue issue

- cardano-wallet/package.json
- cardano-wallet/src/lib.rs
- cardano-wallet/tests/index.js
For Yoroi we need to store `Bip44AccountPublic` and the encrypted version of `Bip44RootPrivateKey` in localstorage for non-hardware wallets so I needed to add `to_hex` functions. I added it to `Bip44AccountPrivate` also just because it'd be strange if one of the account structs didn't have `to_hex` randomly.
I also added code to the test to show how to encrypt/decrypt the mnemonic.
> Add to_hex methods

- cardano-wallet/src/lib.rs
As we discussed, base58 doesn't make sense for these types. Base64 might be convenient to add because that's what we use in Yoroi but right now we construct base64 from converting the output of `to_hex` so it's not that big of a deal either.
> Remove bad tx functions

- cardano-wallet/src/lib.rs
I added this just to make it easy to debug backend requests to our server using the WASM bindings.
> Add from_bytes on SignedTransaction

- cardano-wallet/src/lib.rs
This is based off #64 except now we no longer need the `Inputs` and `Outputs` objects. 
I also in the same PR added constructors for `TxoPointer` and `TxOut` since I thought it was kind of weird they could only be constructed from JSON.
> Input Selection

- cardano-wallet/src/lib.rs
After separating `Witness` into its own class, the signature for creating a witness is now
```
pub fn new_extended_key
blockchain_settings: &BlockchainSettings,
signing_key: &PrivateKey,
transaction_id: &TransactionId,
) -> Witness {
```
So I needed to add a way to get `TransactionId` out of `TransactionFinalized `
> Add missing id() function on TransactionFinalized 

- cardano-wallet/tests/index.js
I made the example code match the logic we use in Yoroi for encrypting/decrypting.
This is just to avoid a different wallet using this example and then we accidentally end up with multiple standards for encryption/decryption
> Match logic with Yoroi

- cardano-wallet/Cargo.toml
- cardano-wallet/README.md
- cardano-wallet/src/lib.rs
- cardano-wallet/tests/index.js
In Yoroi we will need in the future to actually be able to refer to the Bip44 chain as a type so I'm just putting this PR in advance.
I made this as a breaking change (therefore bumping the major version) and since it's a breaking change I figured I might as well remove the deprecated `sign` function.
> Add Bip44 chain support and remove deprecated sign call

- cardano-wallet/src/lib.rs
For Yoroi the Send screen allows the user to author a transaction. Once they've specified the receiver and the amount, they can press the "send" button to broadcast the transaction.
They way I would like this to work internally (currently it's a big hack job) is that the Send page creates a `Transaction` and when they press the "send" button it tries to create a `SignedTransaction`. The problem is that creating a `SignedTransaction` frees the original `Transaction` object so it's not easy to provide a fallback if a tx fails. The cleanest way to solve this is when you press the "send" button, it clones the transaction and tries to sign the clone. If signing fails, it falls back to the original `Transaction`.  
I also added `from_json` in here since probably this will be useful for unit …
> Make txs copyable

- cardano-wallet/Cargo.toml
- cardano-wallet/src/lib.rs
This PR makes it easy to get the master key from a Daedalus mnemonic. I've had to do this fairly often myself also so it seems like it's a useful feature and very simple change.
Here is how you use it.
```
Wallet
.then(Wallet => {
const daedalusMnemonic = 'note park thrive ignore spare latin common balance clap soup school tiny';
const daedalusEntropy = Wallet.Entropy.from_english_mnemonics(daedalusMnemonic);
const daedalusWallet = Wallet.DaedalusWallet.recover(daedalusEntropy);
console.log(daedalusWallet.master_key().to_hex());
})
```
> Add daedalus master key export

- cardano-wallet/src/lib.rs
- wallet-wasm/src/lib.rs
The motivation to change this part of the deprecated `wallet-wasm`
library was the simple introduction of testnet address support in
yoroi-mobile. The alternative is to migrate all of yoroi-mobile away to
use the new `cardano-wallet` module, but this would be significant work
in comparison and can be delayed. Directly adapting
`react-native-cardano` to use `cardano-wallet` was not feasible either
as the API is quite different and would be exceptionally awkward to try
and force into the `react-native-cardano` API that was built on top of
`wallet-wasm` with its API in mind.
Only `xwallet_account()` was changed, as the other function lacking
support for testnet, `wallet_public_to_address()` does not seem to be used
anywhere in `react-native-cardano`, which was the motivation for this change. …
> Testnet address generation

- cardano-wallet/src/lib.rs
Reverts input-output-hk/js-cardano-wasm#82
This did not compile
> Revert "output signed tx in binary format"

- cardano-wallet/Cargo.toml
- cardano-wallet/README.md
- cardano-wallet/src/lib.rs
In Shelley, we often have to do
```
if byron_address
do X
else if shelley_address
do Y
```
The problem is that due to https://github.com/rustwasm/wasm-bindgen/issues/1963 returning a Result that represents an error on the Rust side actually causes stack space to be permanently lost.
This causes Yoroi to crash running out of stack space after some time.
To solve this, I introduce a new function called `is_valid` that instead returns a boolean.
You can tell this fix works based on the following:
```js
let err = null;
for (let j = 0; j < 100000; j++) {
try {
// uncommenting  will not cause a crash
console.log(Wallet.Address.is_valid("asdf"));
// uncommenting this will cause a crash due to lack of stack space
// console.log(Wallet.Address.from_base58("a"));
} catch (e) {
if (err == null) { …
```
> Add is_valid address function
